# Generated by Django 4.2.27 on 2026-01-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
    ]
