# Generated by Django 4.2.27 on 2026-01-26 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0002_expense_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_warning', models.BooleanField(default=True)),
                ('insight_reminders', models.BooleanField(default=True)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('week_start', models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', max_length=10)),
                ('ai_auto_categorization', models.BooleanField(default=True)),
                ('insight_strictness', models.CharField(choices=[('chill', 'Chill'), ('balanced', 'Balanced'), ('strict', 'Strict')], default='balanced', max_length=10)),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='en', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
